### ISSUE TITLE
Profile README Stats not working 

### ISSUE THREAD

**Issue by ghost** [Teoxoy/profile-readme#32]
Hi there,

I am constantly getting a error whenever I am trying to add  profile readme stats:

![image](https://github.com/user-attachments/assets/d79d89e7-6c98-45f6-a2da-89c0eeec8490)

**Comment by teoxoy** [comment]
Is the token you are passing valid? https://github.com/settings/tokens

**Comment by nhelchitnis** [comment]
Which ones would be valid?

**Comment by ghost** [comment]
Yes

**Comment by teoxoy** [comment]
Can you post a link to the action run so I can take a look?

**Comment by ghost** [comment]
[Action link](https://github.com/nhelchitnis/profile-readme-stats/actions/runs/9913285309/job/27389957812)

**Comment by ghost** [comment]
There you go

**Comment by teoxoy** [comment]
Nothing looks off, did you name the token `USER_TOKEN`? Also, try regenerating it.

**Comment by ghost** [comment]
Okay

**Comment by ghost** [comment]
Yes I did

**Comment by ghost** [comment]
It is stilll not working
